# Generated by Django 4.1.2 on 2022-11-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=70)),
                ('domicilio', models.CharField(max_length=70)),
                ('documento', models.CharField(max_length=70)),
                ('mail', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(max_length=30)),
                ('construido', models.CharField(max_length=70)),
                ('titulo_principal', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=70)),
                ('domicilio', models.CharField(max_length=70)),
                ('dni', models.CharField(max_length=70)),
                ('cargo', models.CharField(max_length=70)),
                ('sucursal', models.CharField(max_length=70)),
                ('fecha_nacimiento', models.DateField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_content', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=5000)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=20)),
                ('producto', models.CharField(max_length=100)),
                ('art_fab', models.CharField(max_length=20)),
                ('id_fab', models.CharField(max_length=5)),
                ('costo', models.CharField(max_length=20)),
                ('pvp', models.CharField(max_length=20)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
