# Generated by Django 4.1.2 on 2022-11-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabrica', models.CharField(max_length=30)),
                ('dom_deposito', models.CharField(max_length=60)),
                ('tel_contacto', models.IntegerField()),
                ('mail_pedidos', models.EmailField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.IntegerField(default=' '),
            preserve_default=False,
        ),
    ]
