# Generated by Django 4.1.2 on 2022-11-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_fabricante_empleado_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='fabricante',
            name='tel_contacto',
        ),
    ]
