# Generated by Django 4.1.2 on 2022-11-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_empleado_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fabricante',
            name='tel_dep',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
