# Generated by Django 4.1.2 on 2022-11-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rutina', models.CharField(max_length=50)),
                ('titulo_cabecera', models.CharField(default='', max_length=70)),
                ('construido', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rutina', models.CharField(max_length=50)),
                ('short_content', models.CharField(max_length=70)),
                ('content', models.TextField(max_length=5000)),
                ('image_rutina', models.ImageField(blank=True, null=True, upload_to='post')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
