# Generated by Django 4.1.2 on 2022-11-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracion',
            old_name='nombre_rutina',
            new_name='nombre_del_lugar',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='Boton_menu_1',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracion',
            name='Boton_menu_2',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracion',
            name='Boton_menu_3',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracion',
            name='Boton_menu_4',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracion',
            name='Boton_menu_5',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracion',
            name='Boton_menu_6',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracion',
            name='nombre_de_pagina',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
