# Generated by Django 4.1.2 on 2022-11-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='titulo_secundario',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
