# Generated by Django 4.1.2 on 2022-11-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0002_rename_nombre_rutina_configuracion_nombre_del_lugar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='Boton_menu_1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='Boton_menu_2',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='Boton_menu_3',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='Boton_menu_4',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='Boton_menu_5',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='Boton_menu_6',
            field=models.CharField(max_length=15),
        ),
    ]
