# Generated by Django 4.1.2 on 2022-11-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0002_configuracion_titulo_secundario'),
        ('rutina', '0003_alter_configuracion_boton_menu_1_and_more'),
    ]

    operations = [
    ]
