# Generated by Django 4.1.2 on 2022-11-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0004_merge_20221111_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracion',
            old_name='Boton_menu_1',
            new_name='boton_cabecera_1',
        ),
        migrations.RenameField(
            model_name='configuracion',
            old_name='Boton_menu_2',
            new_name='boton_cabecera_2',
        ),
        migrations.RenameField(
            model_name='configuracion',
            old_name='Boton_menu_3',
            new_name='boton_menu_1',
        ),
        migrations.RenameField(
            model_name='configuracion',
            old_name='Boton_menu_4',
            new_name='boton_menu_2',
        ),
        migrations.RenameField(
            model_name='configuracion',
            old_name='Boton_menu_5',
            new_name='boton_menu_3',
        ),
        migrations.RenameField(
            model_name='configuracion',
            old_name='Boton_menu_6',
            new_name='boton_menu_4',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='boton_menu_5',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracion',
            name='boton_menu_6',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
