# Generated by Django 4.1.2 on 2022-11-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0005_rename_boton_menu_1_configuracion_boton_cabecera_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='boton_cabecera_1',
            field=models.CharField(default='Nombre', max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='boton_cabecera_2',
            field=models.CharField(default='Nombre', max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='boton_menu_1',
            field=models.CharField(default='Nombre', max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='boton_menu_2',
            field=models.CharField(default='Nombre', max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='boton_menu_3',
            field=models.CharField(default='Nombre', max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='boton_menu_4',
            field=models.CharField(default='Nombre', max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='boton_menu_5',
            field=models.CharField(default='Nombre', max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='boton_menu_6',
            field=models.CharField(default='Nombre', max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='nombre_de_pagina',
            field=models.CharField(default='Nombre', max_length=25),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='nombre_del_lugar',
            field=models.CharField(default='Nombre', max_length=50),
        ),
    ]
