# Generated by Django 4.1.2 on 2022-11-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0006_alter_configuracion_boton_cabecera_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='boton_cabecera_1',
            field=models.CharField(default='Nosotros', max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='boton_cabecera_2',
            field=models.CharField(default='Inicio', max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='boton_menu_1',
            field=models.CharField(default='Login', max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='boton_menu_2',
            field=models.CharField(default='Horarios', max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='boton_menu_3',
            field=models.CharField(default='Rutinas', max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='boton_menu_4',
            field=models.CharField(default='Alimentacion', max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='boton_menu_5',
            field=models.CharField(default='Perfil', max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='boton_menu_6',
            field=models.CharField(default='Clientes', max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='nombre_de_pagina',
            field=models.CharField(default='Gym Carrey - Proyecto Final', max_length=25),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='nombre_del_lugar',
            field=models.CharField(default='GYM Carrey', max_length=50),
        ),
    ]
