# Generated by Django 4.1.2 on 2022-11-11 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0007_alter_configuracion_boton_cabecera_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='boton_cabecera_1',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='boton_cabecera_2',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='boton_menu_1',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='boton_menu_2',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='boton_menu_3',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='boton_menu_4',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='boton_menu_5',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='boton_menu_6',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='nombre_de_pagina',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='nombre_del_lugar',
        ),
    ]
