# Generated by Django 4.1.2 on 2022-11-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0008_remove_configuracion_boton_cabecera_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('creador', models.CharField(max_length=70)),
                ('contenido', models.TextField(max_length=5000)),
                ('image_rutina', models.ImageField(blank=True, null=True, upload_to='post')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
