# Generated by Django 4.1.2 on 2022-11-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0009_alimentacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_de', models.CharField(max_length=50)),
                ('horario_de', models.CharField(max_length=40)),
                ('feriados_de', models.CharField(max_length=50)),
            ],
        ),
    ]
