# Generated by Django 4.1.2 on 2022-11-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0010_grilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grilla',
            name='dias_de',
            field=models.CharField(default='Lunes a Sabados', max_length=50),
        ),
        migrations.AlterField(
            model_name='grilla',
            name='feriados_de',
            field=models.CharField(default='9 a 20hs', max_length=50),
        ),
        migrations.AlterField(
            model_name='grilla',
            name='horario_de',
            field=models.CharField(default='de 8 a 22hs', max_length=40),
        ),
    ]
