# Generated by Django 4.1.2 on 2022-11-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0011_alter_grilla_dias_de_alter_grilla_feriados_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentacion',
            name='image_rutina',
            field=models.ImageField(blank=True, null=True, upload_to='rutinas'),
        ),
    ]
