# Generated by Django 4.1.2 on 2022-11-15 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0013_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
