# Generated by Django 4.1.2 on 2022-11-15 07:15

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.list


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rutina', '0014_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListStaff',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', django.views.generic.list.ListView),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
