# Generated by Django 4.1.2 on 2022-11-15 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0015_liststaff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListStaff',
        ),
    ]
