# Generated by Django 4.1.2 on 2022-11-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0017_alter_rutina_image_rutina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentacion',
            name='image_rutina',
            field=models.ImageField(blank=True, null=True, upload_to='post'),
        ),
    ]
