# Generated by Django 4.1.2 on 2022-11-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0018_alter_alimentacion_image_rutina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_staff', models.CharField(default='', max_length=50)),
                ('profe_de', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
